language: php

dist: trusty

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - nightly

matrix:
  allow_failures:
    - php: nightly
    
before_script:
  - composer install --dev --no-interaction
  
script:
  - mkdir -p build/logs
  - phpunit --bootstrap ./tests/bootstrap.php -c tests/phpunit.xml --coverage-clover build/logs/clover.xml tests
  
after_script:
  - php ./vendor/bin/coveralls -v
